### ISSUE TITLE
Error: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by CherryDT** [gpt-engineer-org/gpt-engineer#1260]
## Expected Behavior

Running `gpte .` successfully runs GPT Engineer on the current folder.

## Current Behavior

Running `gpte .` produces this output:

```
Traceback (most recent call last):
  File "/home/david/.local/bin/gpte", line 5, in <module>
    from gpt_engineer.applications.cli.main import app
  File "/home/david/.local/lib/python3.8/site-packages/gpt_engineer/applications/cli/main.py", line 38, in <module>
    from gpt_engineer.applications.cli.cli_agent import CliAgent
  File "/home/david/.local/lib/python3.8/site-packages/gpt_engineer/applications/cli/cli_agent.py", line 4, in <module>
    from gpt_engineer.core.ai import AI
  File "/home/david/.local/lib/python3.8/site-packages/gpt_engineer/core/ai.py", line 12, in <module>
    from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
  File "/home/david/.local/lib/python3.8/site-packages/langchain/callbacks/__init__.py", line 12, in <module>
    from langchain_core.callbacks import (
  File "/home/david/.local/lib/python3.8/site-packages/langchain_core/callbacks/__init__.py", line 22, in <module>
    from langchain_core.callbacks.file import FileCallbackHandler
  File "/home/david/.local/lib/python3.8/site-packages/langchain_core/callbacks/file.py", line 7, in <module>
    from langchain_core.agents import AgentAction, AgentFinish
  File "/home/david/.local/lib/python3.8/site-packages/langchain_core/agents.py", line 31, in <module>
    from langchain_core.messages import (
  File "/home/david/.local/lib/python3.8/site-packages/langchain_core/messages/__init__.py", line 18, in <module>
    from langchain_core.messages.ai import (
  File "/home/david/.local/lib/python3.8/site-packages/langchain_core/messages/ai.py", line 11, in <module>
    from langchain_core.messages.tool import (
  File "/home/david/.local/lib/python3.8/site-packages/langchain_core/messages/tool.py", line 10, in <module>
    class ToolMessage(BaseMessage):
  File "pydantic/main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 641, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

## Failure Information

All defaults.

### Failure Logs

There is no such file.

## System Information

Same error as above appears when running `gpte --sysinfo`.

But I can tell you it is Ubuntu 20.04 on WSL1 on Windows 10, with Python 3.8.

## Installation Method

Installed using `pip install`.

**Comment by CherryDT** [comment]
Tweaking the dependency versions I had installed eventually resulted in a usable version.
