### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'FilesDict' and 'FilesDict'

### ISSUE THREAD

**Issue by marcel-yay** [gpt-engineer-org/gpt-engineer#912]
I ve set up gpt-engineer with python -v 3.8.12.
On command `gpte projects/project-folder` everything runs as expected.
Suddenly, the script breaks stating: 

```
Traceback (most recent call last):

  File "/Users/reperich/Library/Caches/pypoetry/virtualenvs/gpt-engineer-vjBHF-X4-py3.8/bin/gpte", line 6, in <module>
    sys.exit(app())

  File "/Users/reperich/Documents/gpt-engineer/gpt_engineer/applications/cli/main.py", line 196, in main
    files_dict = agent.init(prompt)

  File "/Users/reperich/Documents/gpt-engineer/gpt_engineer/applications/cli/cli_agent.py", line 116, in init
    files_dict = FilesDict(files_dict | entrypoint)

TypeError: unsupported operand type(s) for |: 'FilesDict' and 'FilesDict'

```

No workspace with files is created.

How to solve this issue?

**Comment by ErikBjare** [comment]
See #898, and use Python 3.10.

**Comment by ATheorell** [comment]
This should now be fixed both on GH  main and pypi
